# version: '2'

# services:
#   app:
#     image: 'hms:latest'
#     build:
#       context: .
#     container_name: app
#     depends_on:
#       - db
#     environment:
#       - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/db_hms
#       - SPRING_DATASOURCE_USERNAME=leng
#       - SPRING_DATASOURCE_PASSWORD=leng
#       - SPRING_JPA_HIBERNATE_DDL_AUTO=update
          
#   db:
#     image: postgres
#     container_name: db
#     environment:
#       - POSTGRES_USER=leng
#       - POSTGRES_PASSWORD=leng
# version: '3.9'

# services:
#   db:
#     container_name: "scschscsjcjs"
#     image: postgres
#     restart: always
#     environment:
#       POSTGRES_USER: leng
#       POSTGRES_PASSWORD: leng
#       POSTGRES_DB: db_hms
#     ports:
#       - "5432:5432"
#     volumes:
#       - C:\postgres-data:/var/lib/postgresql/data
#   app:
#     container_name: "testsss"
#     build:
#       dockerfile: Dockerfile
#       context: .
#     links:
#       - "db:database"
#     depends_on:
#       - db
#     ports:
#       - 8080:8080
#     command: /home/gradle/buildWorkspace/app/build/distributions/app/bin/app

version: '3.9'

services:
  hms_app:
    container_name: hms_app_container
    image: horleng/hms_app:1.0.0
    build: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/db_cms
      - DATABASE_USERNAME=leng
      - DATABASE_PASSWORD=leng
    depends_on:
      - db
  db:
    container_name: postgres-db
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: leng
      POSTGRES_PASSWORD: leng
      POSTGRES_DB: hms
    volumes:
      - C:\postgres-data:/var/lib/postgresql/data

volumes:
  pgdata: {}